TrainerAssignment/Models/Trainer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace TrainerAssignment.Models
{
    public class Trainer
    {
        public int TrainerId { get; set; }
        [Required(ErrorMessage ="This Field Cannot be empty"),MaxLength(20),MinLength(3)]
        [Display(Name ="First Name")]
        [RegularExpression("^[a-zA-Z]+$", ErrorMessage = "only alphabet")]
        [CustomValidation(typeof(MyValidationMethods.MyValidationMethods),"FirstLetterCapital")]
       
        public string FirstName { get; set; }
        [CustomValidation(typeof(MyValidationMethods.MyValidationMethods), "FirstLetterCapital")]
        
        [Required(ErrorMessage = "This Field Cannot be empty"), MaxLength(20), MinLength(3)]
        [Display(Name = "Last Name")]
        [RegularExpression("^[a-zA-Z]+$", ErrorMessage = "Only alphabet")]
        public string LastName { get; set; }
        
        [CustomValidation(typeof(MyValidationMethods.MyValidationMethods), "ValidateSalary")]
        public decimal Salary { get; set; }
        [Required(ErrorMessage ="This field Cannot be empty")]
        [Display(Name ="DateHire")]
        [DisplayFormat(DataFormatString ="{0:MM/dd/yyyy}")]
        public DateTime DateHire { get; set; }
        [Required(ErrorMessage = "This field Cannot be empty")]
        [Display(Name ="Is Available")]
        public bool IsAvailable { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
    }
}

TrainerAssignment/Controllers/TrainerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainerAssignment.DAL;
using TrainerAssignment.Models;
using TrainerAssignment.Models.ViewModels;
using PagedList;

namespace TrainerAssignment.Controllers
{
    public class TrainerController : Controller
    {
        private MyDatabase db = new MyDatabase();

        // GET: Trainer
        public ActionResult Index(string searchFirstName,string searchLastName,int?searchMinSalary,int? searchMaxSalary,DateTime? searchMaxDate,DateTime? searchMinDate ,string sortOrder,int?pSize,int?page)
        {
            List<Trainer> trainers = Filtering(searchFirstName, searchLastName, searchMinSalary, searchMaxSalary,searchMaxDate,searchMinDate ,sortOrder);

            //Filtering
            trainers = Filter(searchFirstName, searchLastName, searchMinSalary, searchMaxSalary,searchMaxDate,searchMinDate ,trainers);
            //Sorting
            trainers = Sorting(sortOrder, trainers);

            //pagination
            int pageSize, pageNumber;
            Pagination(pSize, page, out pageSize, out pageNumber);

            return View(trainers.ToPagedList(pageNumber, pageSize));
        }

        private static void Pagination(int? pSize, int? page, out int pageSize, out int pageNumber)
        {
            pageSize = pSize ?? 5;
            pageNumber = page ?? 1;
        }

        private static List<Trainer> Sorting(string sortOrder, List<Trainer> trainers)
        {
            switch (sortOrder)
            {
                case "FirstNameDesc": trainers = trainers.OrderByDescending(x => x.FirstName).ToList(); break;
                case "LastNameAsc": trainers = trainers.OrderBy(x => x.LastName).ToList(); break;
                case "LastNameDesc": trainers = trainers.OrderByDescending(x => x.LastName).ToList(); break;

                case "SalaryAsc": trainers = trainers.OrderBy(x => x.Salary).ToList(); break;
                case "SalaryDesc": trainers = trainers.OrderByDescending(x => x.Salary).ToList(); break;
                case "DateHireAsc":trainers = trainers.OrderBy(x => x.DateHire).ToList();break;
                case "DateHireDesc":trainers = trainers.OrderByDescending(x => x.DateHire).ToList();break;
                default: trainers = trainers.OrderBy(x => x.FirstName).ToList(); break;
            }

            return trainers;
        }

        private static List<Trainer> Filter(string searchFirstName, string searchLastName, int? searchMinSalary, int? searchMaxSalary, DateTime? searchMaxDate, DateTime? searchMinDate ,List<Trainer> trainers)
        {
            if (!String.IsNullOrEmpty(searchFirstName))
            {
                trainers = trainers.Where(x => x.FirstName.ToUpper().Contains(searchFirstName.ToUpper())).ToList();
            }
            if (!String.IsNullOrEmpty(searchLastName))
            {
                trainers = trainers.Where(x => x.LastName.ToUpper().Contains(searchLastName.ToUpper())).ToList();
            }
            if (!(searchMinSalary is null))
            {
                trainers = trainers.Where(x => x.Salary >= searchMinSalary).ToList();
            }
            if (!(searchMaxSalary is null))
            {
                trainers = trainers.Where(x => x.Salary <= searchMaxSalary).ToList();
            }
            if(!(searchMaxDate is null))
            {
                trainers = trainers.Where(x => x.DateHire >= searchMinDate).ToList();
            }
            if(!(searchMinDate is null))
            {
                trainers = trainers.Where(x => x.DateHire <= searchMaxDate).ToList();
            }

            return trainers;
        }

        private List<Trainer> Filtering(string searchFirstName, string searchLastName, int? searchMinSalary, int? searchMaxSalary,DateTime? searchMaxDate, DateTime? searchMinDate , string sortOrder)
        {
            var trainers = db.Trainers.ToList();
            ViewBag.FNSP = String.IsNullOrEmpty(sortOrder) ? "FirstNameDesc" : "";
            ViewBag.LNSP = sortOrder == "LastNameAsc" ? "LastNameDesc" : "LastNameAsc";
            ViewBag.SNSP = sortOrder == "SalaryAsc" ? "SalaryDesc" : "SalaryAsc";
            ViewBag.DNSP = sortOrder == "DateHireAsc" ? "DateHireDesc" : "DateHireAsc";

            ViewBag.CurrentFirstName = searchFirstName;
            ViewBag.CurrentLastName = searchLastName;
            ViewBag.CurrentMinSalary = searchMinSalary;
            ViewBag.CurrentMaxSalary = searchMaxSalary;
            ViewBag.CurrentSortOrder = sortOrder;
            ViewBag.CurrentMaxDate = searchMaxDate;
            ViewBag.CurrentMinDate = searchMinDate;
            return trainers;
        }

        // GET: Trainer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = db.Trainers.Find(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        // GET: Trainer/Create
        public ActionResult Create()
        {
            TrainerCreateViewModel vm = new TrainerCreateViewModel();
            return View(vm);
        }

        // POST: Trainer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TrainerId,FirstName,LastName,Salary,DateHire,IsAvailable")] Trainer trainer,IEnumerable<int> SelectSubjectsIds)
        {
            if (ModelState.IsValid)
            {
                db.Trainers.Attach(trainer);
                db.Entry(trainer).Collection("Categories").Load();
                trainer.Categories.Clear();
               if(!(SelectSubjectsIds is null))
                {
                    foreach(var id in SelectSubjectsIds)
                    {
                        Category category = db.Categories.Find(id);
                        if (trainer != null)
                        {
                            trainer.Categories.Add(category);
                        }
                    }
                }
                db.Entry(trainer).State = EntityState.Added;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            TrainerCreateViewModel vm = new TrainerCreateViewModel();
            return View(vm);
        }

        // GET: Trainer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = db.Trainers.Find(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            TrainerEditViewModel vm = new TrainerEditViewModel(trainer);
            return View(vm);
        }

        // POST: Trainer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TrainerId,FirstName,LastName,Salary,DateHire,IsAvailable")] Trainer trainer,IEnumerable<int> SelectSubjectsIds)
        {
            if (ModelState.IsValid)
            {
                db.Trainers.Attach(trainer);
                db.Entry(trainer).Collection("Categories").Load();
                trainer.Categories.Clear();
                db.SaveChanges();
                if (!(SelectSubjectsIds is null))
                {
                    foreach (var id in SelectSubjectsIds)
                    {
                        Category category = db.Categories.Find(id);
                        if (trainer != null)
                        {
                            trainer.Categories.Add(category);
                        }
                    }
                }
                db.Entry(trainer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            db.Trainers.Attach(trainer);
            db.Entry(trainer).Collection("Categories").Load();
            TrainerEditViewModel vm = new TrainerEditViewModel(trainer);
            return View(vm);
        }

        // GET: Trainer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = db.Trainers.Find(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        // POST: Trainer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trainer trainer = db.Trainers.Find(id);
            db.Trainers.Remove(trainer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrainerAssignment/Views/Trainer/Create.cshtml
@model TrainerAssignment.Models.ViewModels.TrainerCreateViewModel

@{
    ViewBag.Title = "Create";
}
<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Trainer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Trainer.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Trainer.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Trainer.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Trainer.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Trainer.Salary, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Trainer.Salary, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.DateHire, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Trainer.DateHire, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Trainer.DateHire, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.Trainer.IsAvailable, new { htmlAttributes = new { @class = "form-control", } })
            @Html.ValidationMessageFor(model => model.Trainer.IsAvailable, "", new { @class = "text-danger" })
        </div>
    </div>   
    <div class="form-group">
        @Html.Label("SelectSubjectsIds", "Subject", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.ListBox("SelectSubjectsIds", null, htmlAttributes: new { @class = "form-control", size = "20" })
                @Html.ValidationMessageFor(model => model.Trainer.TrainerId, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TrainerAssignment/Views/Trainer/Delete.cshtml
@model TrainerAssignment.Models.Trainer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trainer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateHire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateHire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TrainerAssignment/Views/Trainer/Details.cshtml
@model TrainerAssignment.Models.Trainer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Trainer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateHire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateHire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>
        <dt>
         Subject
        </dt>
        <dd>
            <ul>
                @foreach (var subject in Model.Categories)
                {
                    <li>@subject.Subject</li>
                }
            </ul>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TrainerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TrainerAssignment/Views/Trainer/Edit.cshtml
@model TrainerAssignment.Models.ViewModels.TrainerEditViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Trainer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Trainer.TrainerId)

    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Trainer.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Trainer.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Trainer.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Trainer.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Trainer.Salary, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Trainer.Salary, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.DateHire, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Trainer.DateHire, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Trainer.DateHire, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Trainer.IsAvailable)
                @Html.ValidationMessageFor(model => model.Trainer.IsAvailable, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.Label("SelectSubjectsIds", "Subject", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.ListBox("SelectSubjectsIds", null, htmlAttributes: new { @class = "form-control", size = "20" })
                 @Html.ValidationMessageFor(model => model.Trainer.TrainerId, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to Index", "Index")
</div>

TrainerAssignment/Views/Trainer/Index.cshtml
@model PagedList.IPagedList<TrainerAssignment.Models.Trainer>
@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { @class = "form-group" })
</p>
@using (@Html.BeginForm("Index", "Trainer", FormMethod.Get, new { @class = "form-group" }))
{

    @Html.TextBox("searchFirstName", null, new { @class = "form-control", placeholder = "Search First Name", type = "search" });
    <br />
    @Html.TextBox("searchLastName", null, new { @class = "form-control", placeholder = "Search Last Name", type = "search" });
    <br />
    @Html.TextBox("searchMinSalary", null, new { @class = "form-control", placeholder = "Search Minimum Salary", type = "number" });
    <br />
    @Html.TextBox("searchMaxSalary", null, new { @class = "form-control", placeholder = "Search Maximum Salary", type = "number" });
    <br />   
    @Html.TextBox("searchMaxDate", null, new { @class = "form-control", placeholder = "Search Max Date", type = "date" });
    <br />
    @Html.TextBox("searchMinDate", null, new { @class = "form-control", placeholder = "Search Max Date", type = "date" });
    <br />
    <input type="hidden" name="sortOrder" value="@ViewBag.CurrentSortOrder" />
    <input type="submit" value="Search Trainer" class="btn btn-primary" />
    <input id="ResetButton" type="button" value="Clear Form" class="btn btn-success" />
}
@if (!(Model.PageCount < Model.PageNumber))
{
    <table class="table">

        <tr>
            <th>
                @Html.ActionLink("First Name", "Index", "Trainer", new { sortOrder = ViewBag.FNSP, searchFirstName = ViewBag.CurrectFirstName, searchLastName = ViewBag.CurrectLastName, searchMinSalary = ViewBag.CurrectMinSalary, searchMaxSalary = ViewBag.CurrectMaxSalary }, null)
            </th>
            <th>
                @Html.ActionLink("Last Name", "Index", "Trainer", new { sortOrder = ViewBag.LNSP, searchFirstName = ViewBag.CurrectFirstName, searchLastName = ViewBag.CurrectLastName, searchMinSalary = ViewBag.CurrectMinSalary, searchMaxSalary = ViewBag.CurrectMaxSalary }, null)
            </th>
            <th>
                @Html.ActionLink("Salary", "Index", "Trainer", new { sortOrder = ViewBag.SNSP, searchFirstName = ViewBag.CurrectFirstName, searchLastName = ViewBag.CurrectLastName, searchMinSalary = ViewBag.CurrectMinSalary, searchMaxSalary = ViewBag.CurrectMaxSalary }, null)
            </th>
            <th>
                @Html.ActionLink("Date Hire", "Index", "Trainer", new { sortOrder = ViewBag.SNSP, searchFirstName = ViewBag.CurrectFirstName, searchLastName = ViewBag.CurrectLastName, searchMinSalary = ViewBag.CurrectMinSalary, searchMaxSalary = ViewBag.CurrectMaxSalary, searchMinDate = ViewBag.CurrentMinDate, searchMaxDate = ViewBag.CurrentMaxDate }, null)
            </th>
            <th>
                Is Available
            </th>
            <th>
                Subject
            </th>
            <th>
                Actions
            </th>
        </tr>


        @foreach (var trainer in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => trainer.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => trainer.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => trainer.Salary)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => trainer.DateHire)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => trainer.IsAvailable)
                </td>
                <td>
                    <ul>
                        @foreach (var subject in trainer.Categories)
                        {
                            <li>@subject.Subject</li>
                        }
                    </ul>
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = trainer.TrainerId },new { @class = "btn btn-primary" }) |
                    @Html.ActionLink("Details", "Details", new { id = trainer.TrainerId }, new { @class = "btn btn-info" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = trainer.TrainerId }, new { @class = "btn btn-danger", @onclick = "DeleteButton()" })
                </td>
            </tr>
        }

    </table>

}
else
{
    <h1>No Data in This Page</h1>
}
Page @(Model.PageCount<Model.PageNumber?0:Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, x => Url.Action("Index", "Trainer", new { page = x }))
@Html.ActionLink("Back To Index", "Index", "Trainer")

@section MyCustomJavascript{
    <script>
        $("#ResetButton").click(function (e) {
            $("#searchFirstName").val("");
            $("#searchLastName").val("");
            $("#searchMinSalary").val("");
            $("#searchMaxSalary").val("");
            $("#searchMaxDate").val("");
            $("#searchMinDate").val("");

        });
        function DeleteButton() {
            alert("Are u sure u want to delete this row?");
        }
    </script>
}